# Generated by Django 3.2.6 on 2022-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
    ]
